#+OPTIONS: author:nil timestamp:nil

Welcome to Rincanter!

* About
  Rincanter is a clojure/incanter wrapper around the rosuda JRIEngine
  Java/R bridge. The hope is to allow easy access to an embedded R
  engine from incanter. It also offers translation between
  clojure/incanter datatypes and R datatypes such as R dataframe to
  incanter dataset.
* Install
  As rincanter sits on top the org.rosuda JRI and JRIEngine packages,
  you will need install these to use rincanter. This can be a bit
  tricky, as the JRI component needs to compile some native JNI libs
  and install them on the java.library.path in order to run.
** Download and Install the rosuda JRI and REngine components
   
   You will need to download and build the rosuda JRIEngine
   components:

#+BEGIN_EXAMPLE 
   svn co svn://svn.rforge.net/org/trunk/rosuda/REngine
   svn://svn.rforge.net/org/trunk/rosuda/JRI
   cd JRI
   configure && make
#+END_EXAMPLE

You will now have a jri library file in this directory. Depending on
your platform it will have a name like: libjri.so (linux)
libjri.jnilib (Mac OS X) jri.dll (Windows)

#+BEGIN_EXAMPLE 
  cd ../REngine
  configure && make
#+END_EXAMPLE

You will now have an REngine.jar file in this directory.

#+BEGIN_EXAMPLE 
  cd JRI # this is a child dir of REngine, different from the JRI dir above
  configure && make
#+END_EXAMPLE

You will now have an JRIEngine.jar file in this directory.

** Install incanter from git
I am using features in incanter that are in git but not up on clojars
yet. You will need to pull incanter from github and from the incanter
directory run:

#+BEGIN_EXAMPLE 
  lein install
#+END_EXAMPLE

** Install rincanter from git

#+BEGIN_EXAMPLE 
   git clone git@github.com:jolby/rincanter.git
   cd rincanter
   lein deps # this installs incanter and its deps into the lib subdir
#+END_EXAMPLE

Now, move the two .jar files (REngine.jar and JRIEngine.jar) into the
lib directory of the rincanter project. Then move the native jri lib
into the root of the rincanter project.

Now you are ready to download rincanter and run it:

#+BEGIN_EXAMPLE 
  lein test
#+END_EXAMPLE

To start a swank-repl: 

#+BEGIN_EXAMPLE 
  lein repl
#+END_EXAMPLE


* Example Usage
* Documentation
** API Documentation
   API Documentation for rincanter is located at:
   [[http://jolby.github.com/rincanter][Rincanter API]]
